// Dati del sito. Il template (index.html) legge solo questo file.
window.SITE = {
  layout: "mare",
  name: "Pizzeria Ristorante Titanic",
  shortName: "Titanic",
  tagline: "Pizzeria · Ristorante",
  since: "1998",
  city: "Torino",
  seoTitle: "Pizzeria Ristorante Titanic · Torino dal 1998",
  seoDescription: "Pizzeria Ristorante Titanic, Via Frejus 106/i Torino. Pizza al forno a legna con farina macinata a pietra, farinata e specialità di pesce dal 1998.",
  logo: "img/logo.webp",
  address: "Via Frejus 106/i, 10139 Torino",
  addressShort: "Via Frejus 106/i, Torino",
  addressLead: "Con parcheggio interno riservato ai clienti.",
  mapsQuery: "Pizzeria Ristorante Titanic, Via Frejus 106, Torino",
  phone: "011 383 5787",
  phoneIntl: "+390113835787",
  whatsapp: "",
  email: "pizzatitanic@gmail.com",
  social: { facebook: "https://www.facebook.com/PizzeriaRistoranteTitanic/", instagram: "https://www.instagram.com/titanicpizzeria1998/" },
  piva: "",
  footerLine: "L'equipaggio augura a tutti voi buon appetito e buon viaggio",
  rating: { value: "4,2", count: "oltre 600", source: "Google" },
  theme: { primary: "#16233b", primaryDark: "#0f1829", accent: "#b88a3b", accentLight: "#e7c98e", soft: "#e9eef3", cream: "#f6f1e7", paper: "#fbf8f2", line: "#e3dccd" },

  hero: {
    image: "img/sala.webp",
    imageAlt: "La sala del Titanic con il soffitto a cielo stellato e gli iceberg dipinti",
    eyebrow: "Via Frejus · Torino · dal 1998",
    title: "La rotta del gusto",
    titleEm: "parte da qui",
    lead: "Pizza al forno a legna con farina macinata a pietra, farinata croccante e cucina di mare, in una sala che sembra il ponte di una nave.",
    cta: "Prenota o ordina",
    badges: ["Forno a legna", "Specialità di pesce", "Asporto", "Parcheggio interno"]
  },

  pillars: [
    { t: "Farina macinata a pietra", d: "Tipo 2: più saporita, più ricca e più digeribile." },
    { t: "Forno a legna", d: "Pizze cotte come si deve, anche al padellino su richiesta." },
    { t: "Farinata", d: "Croccante fuori e morbida dentro, come vuole la tradizione." },
    { t: "Cucina di mare", d: "Crudi, primi, fritture e grigliate di pesce per chi ama il mare." }
  ],

  story: {
    image: "img/forno.webp",
    imageAlt: "Pizze appena sfornate dal forno a legna",
    eyebrow: "L'equipaggio vi aspetta",
    title: "Dal 1998 a Torino, con la stessa passione",
    paragraphs: [
      "Da oltre venticinque anni accogliamo famiglie, amici e habitué in due grandi sale dedicate al mare e in un ampio dehors estivo coperto.",
      "Il nostro segreto è semplice: <strong>solo farina macinata a pietra</strong>. La macinazione lenta conserva il germe del grano, la parte più nobile del seme, ricca di vitamine e sali minerali. Il risultato è un impasto profumato, leggero e facile da digerire."
    ],
    bullets: ["Impasto integrale ai cereali su richiesta", "Due sale a tema e dehors estivo coperto", "Parcheggio interno per i clienti", "Pizze e farinata anche da asporto"]
  },

  menu: {
    eyebrow: "Il menù",
    title: "Dalla cambusa del Titanic",
    lead: "Oltre 60 pizze, focacce e farinata, antipasti, primi e secondi di mare e di terra. Prezzi in euro.",
    pdf: "img/menu-titanic.pdf",
    notes: [
      "* Prodotto surgelato. Talvolta alcuni prodotti freschi non sono reperibili sul mercato e possono essere sostituiti con prodotti surgelati.",
      "Coperto € 1,50 · Origano su tutte le pizze a richiesta · Pizza al padellino su richiesta.",
      "Alcuni ingredienti possono contenere allergeni (cereali, uova, crostacei, sedano, soia, latticini, arachidi, senape, lupini, frutta a guscio, molluschi). Chiedete al personale la documentazione sugli allergeni."
    ],
    categories: [
 {id:"pizze", t:"Pizze", s:"Pizze", note:"Farina macinata a pietra tipo 2 · origano a richiesta", items:[
  ["Marinara","5,00","pomodoro, aglio, origano, olio EVO"],
  ["Margherita","6,00","pomodoro, mozzarella, olio EVO"],
  ["Olive","6,50","pomodoro, mozzarella, olive, olio EVO"],
  ["Cipolla","6,50","pomodoro, mozzarella, cipolla, olio EVO"],
  ["Campagnola","6,50","pomodoro, pomodoro fresco, aglio, parmigiano, basilico, olio EVO"],
  ["Rucola","7,00","pomodoro fresco, mozzarella, rucola, olio EVO"],
  ["Funghi","7,00","pomodoro, mozzarella, funghi, olio EVO"],
  ["Prosciutto","7,00","pomodoro, mozzarella, prosciutto, olio EVO"],
  ["Salamino","7,00","pomodoro, mozzarella, salamino, olio EVO"],
  ["Napoletana","7,00","pomodoro, mozzarella, acciughe, olio EVO"],
  ["Margherita con bufala","7,00","pomodoro, mozzarella di bufala, olio EVO"],
  ["Prosciutto e funghi","7,50","pomodoro, mozzarella, prosciutto, funghi, olio EVO"],
  ["Parmigiana","8,00","pomodoro, mozzarella, melanzane, parmigiano, olio EVO"],
  ["La Bufala","8,00","pomodoro fresco, mozzarella di bufala, basilico, olio EVO"],
  ["Canadese","8,00","pomodoro, mozzarella, prosciutto, würstel, olio EVO"],
  ["Quattro stagioni","8,00","pomodoro, mozzarella, prosciutto, funghi, olive, carciofi, olio EVO"],
  ["Bismark","8,00","pomodoro, mozzarella, prosciutto, uovo, olio EVO"],
  ["Calzone","8,00","pomodoro, mozzarella, prosciutto, funghi, olio EVO"],
  ["Siciliana","8,00","pomodoro, mozzarella, capperi, acciughe, olive, olio EVO"],
  ["Stracchino e rucola","8,00","pomodoro fresco, mozzarella, stracchino, rucola, olio EVO"],
  ["Quattro formaggi","8,00","pomodoro, mozzarella, gorgonzola, berna, olandese, olio EVO"],
  ["Valdostana","8,00","pomodoro, mozzarella, prosciutto, fontina, olio EVO"],
  ["Saporita","8,00","pomodoro, mozzarella, salsiccia fresca, patate, prezzemolo, olio EVO"],
  ["Ligure","8,00","mozzarella, pesto, olive taggiasche, patate"],
  ["Gorgonzola e cipolla","8,50","pomodoro, mozzarella, gorgonzola, cipolla, olio EVO"],
  ["Gorgonzola e pere","8,50","mozzarella, gorgonzola, pera"],
  ["Greca","8,50","pomodoro, mozzarella, tonno, uova sode, olive, olio EVO"],
  ["Capricciosa","8,50","pomodoro, mozzarella, prosciutto, funghi, salamino, carciofi, olive, olio EVO"],
  ["Maratona","8,50","pomodoro, mozzarella, prosciutto, salamino, fontina, olio EVO"],
  ["Mediterranea","8,50","pomodoro, mozzarella, tonno, cipolla, olio EVO"],
  ["Filadelfia","8,50","pomodoro, mozzarella, gorgonzola, salamino, funghi, olio EVO"],
  ["La Gustosa","8,50","mozzarella, patate, gorgonzola, olio EVO"],
  ["Verdure","8,50","pomodoro fresco, mozzarella, verdure grigliate, olio EVO"],
  ["Diavola","8,50","pomodoro, mozzarella, funghi, peperoni arrostiti, salamino, olio EVO"],
  ["Salsiccia e friarielli","8,50","mozzarella, salsiccia, friarielli, aglio, olio EVO"],
  ["Sfiziosa","8,50","pomodoro, mozzarella, stracchino, speck, olio EVO"],
  ["Patapizza","9,00","pomodoro, mozzarella, patatine fritte*"],
  ["La Delizia","9,00","pomodoro, mozzarella, gamberi*, rucola, olio EVO"],
  ["Gorgonzola e noci","9,00","mozzarella, gorgonzola, noci"],
  ["Tirolese","9,00","mozzarella, gorgonzola, radicchio, speck, olio EVO"],
  ["Trevisana","9,00","pomodoro fresco, mozzarella, radicchio, provola, olio EVO"],
  ["Zucchine e lardo","9,00","pomodoro fresco, mozzarella, zucchine, lardo, olio EVO"],
  ["Zenzero","10,00","mozzarella, zenzero, caprino, miele"],
  ["Crudo di Parma","10,00","pomodoro, mozzarella, prosciutto crudo di Parma"],
  ["La Porcini","13,00","mozzarella, funghi porcini*, aglio, prezzemolo, olio EVO"],
  ["Valtellina","13,00","pomodoro fresco, mozzarella, bresaola, rucola, scaglie di parmigiano"],
  ["Pescatora","15,00","pomodoro, frutti di mare*, prezzemolo, aglio, olio EVO"],
 ], extra:"Impasto integrale ai cereali +€ 1,00 · Aggiunte: mozzarella di bufala € 2,00 · patatine fritte € 3,00 · crudo di Parma € 3,00"},
 {id:"speciali", t:"Le Speciali", s:"Speciali", items:[
  ["Titanic","18,00","la pizza della casa: chiedete all'equipaggio*","Firma"],
  ["Calabrese","13,00","pomodoro, 'nduja e burrata"],
  ["Italy","13,00","pomodoro passato, pachino, rucola, prosciutto crudo di Parma, burrata"],
  ["Stamberga","13,00","quattro spicchi: quattro formaggi, greca, pescatora, capricciosa, asparagi*"],
  ["Bolognese","12,00","mozzarella, mortadella, burrata, pistacchio"],
  ["Montanara","10,00","mozzarella, lardo, caprino e miele"],
  ["Burrata","8,00","pomodoro e burrata"],
 ]},
 {id:"farinata", t:"Focacce e Farinata", s:"Farinata e focacce", note:"Farina macinata a pietra tipo 2", items:[
  ["Farinata","4,00","","Tradizione"],
  ["Focaccia al rosmarino","4,00","farina, sale, olio EVO, rosmarino"],
  ["Focaccia all'origano","4,00","farina, sale, olio EVO, origano"],
  ["Focaccia al lardo","7,00","farina, olio EVO, lardo"],
  ["Focaccia pachino e rucola","7,00","farina, sale, olio EVO, pomodoro pachino e rucola"],
  ["Focaccia allo speck","8,00","farina, olio EVO, speck"],
  ["Focaccia alla mortadella","8,00","farina, sale, olio EVO, mortadella"],
  ["Focaccia al crudo di Parma","9,00","farina, olio EVO, crudo di Parma"],
 ]},
 {id:"antipasti", t:"Antipasti", s:"Antipasti", items:[
  ["Ostriche","3,50 cad.",""],
  ["Antipasto misto di mare*","15,00",""],
  ["Tagliere misto","15,00","affettati e formaggi"],
  ["Insalata di mare*","14,00",""],
  ["Crudo di Parma con burrata e chiacchiere","13,00",""],
  ["Bresaola e rucola","13,00","con scaglie di grana"],
  ["Tartare di tonno*","12,00","capperi e olive"],
  ["Zuppa di cozze","12,00",""],
  ["Insalata di polipo* e patate","12,00",""],
  ["Carpaccio di spada*","12,00","pachino e rucola"],
  ["Impepata di cozze","10,00",""],
  ["Cocktail di gamberetti*","9,00",""],
  ["Bufala intera","8,00",""],
 ]},
 {id:"primi", t:"Primi e Pasta fresca", s:"Primi", items:[
  ["Pennette al salmone","10,00",""],
  ["Pennette del marinaio","13,00","pomodori, polipo*, melanzane, olive taggiasche"],
  ["Spaghetti alle vongole veraci","14,00",""],
  ["Linguine agli scampi e funghi porcini*","15,00",""],
  ["Linguine all'astice","18,00",""],
  ["Risotto castelmagno e funghi porcini*","12,00",""],
  ["Risotto alla pescatora*","15,00",""],
  ["Paella*","18,00","a persona, minimo 2 persone"],
  ["Scialatelli ai frutti di mare*","15,00","pasta fresca"],
  ["Scialatelli alle vongole","15,00","pasta fresca, pistacchio e pomodori secchi"],
  ["Orecchiette alla pugliese","10,00","melanzane, olive taggiasche, pancetta, ricotta salata"],
  ["Orecchiette con broccoli e gamberi","12,00",""],
  ["Tagliolini con gamberi* e zucchine","12,00",""],
  ["Tagliolini ai funghi porcini*","12,00",""],
  ["Gnocchi al pesto con calamaretti* e pachino","12,00",""],
  ["Gnocchi al gorgonzola, speck e noci","10,00",""],
 ]},
 {id:"pesce", t:"Pesce", s:"Pesce", items:[
  ["Grigliata mista di pesce*","25,00",""],
  ["Fritto di calamari e gamberi*","18,00",""],
  ["Fritto misto di mare*","18,00",""],
  ["Zuppetta di mare*","18,00",""],
  ["Pescespada* gratinato al lime","18,00",""],
  ["Pescespada* ai funghi porcini*","18,00",""],
  ["Branzino sfilettato ai funghi porcini*","18,00",""],
  ["Filetto di rombo alle quattro stagioni in crosta","18,00",""],
  ["Tagliata di tonno* al sesamo e pistacchi","16,00",""],
  ["Tagliata di tonno* alle verdure","16,00",""],
  ["Branzino sfilettato alla ligure","16,00",""],
  ["Salmone alla griglia","15,00",""],
 ]},
 {id:"carne", t:"Carne e Contorni", s:"Carne e contorni", items:[
  ["Sottofiletto ai funghi porcini*","16,00",""],
  ["Sottofiletto alla griglia","15,00",""],
  ["Tagliata di vitello con verdure","15,00",""],
  ["Tagliata di vitello con radicchio","15,00","parmigiano e glassa al balsamico"],
  ["Tagliata di vitello con rucola e pachino","15,00",""],
  ["Cotoletta alla milanese","13,00","con rucola e pachino"],
  ["Insalata con rucola, gamberetti* e carote","9,00",""],
  ["Insalata mediterranea","8,00","insalata verde, pomodori, mais, tonno, cipolla"],
  ["Nizzarda","8,00","insalata verde, pomodori, uova, tonno, olive, mozzarella"],
  ["Misto di verdure grigliate","7,00",""],
  ["Insalata mista","4,50",""],
  ["Insalata verde","4,00",""],
  ["Patate al forno","4,00",""],
  ["Patate prezzemolate","4,00",""],
  ["Patatine fritte*","4,00",""],
  ["Spinaci* al burro","4,00",""],
 ]},
 {id:"dessert", t:"Dessert e Caffetteria", s:"Dolci", items:[
  ["Dolci della casa","5,00",""],
  ["Affogati","6,00",""],
  ["Caffè","1,50",""],
  ["Amari","3,00",""],
  ["Grappe","3,00",""],
 ]},
 {id:"bevande", t:"Birre e Bevande", s:"Bevande", items:[
  ["Menabrea bionda","3,50 · 5,00","piccola 0,20 L · media 0,40 L"],
  ["Menabrea rossa","4,00 · 6,00","piccola 0,20 L · media 0,40 L"],
  ["Birre in bottiglia","4,00","cl 33"],
  ["Coca-Cola alla spina","3,00 · 4,00","piccola · media"],
  ["Bibite in bottiglia","3,00","cl 33 · Coca-Cola, Fanta, Sprite, Coca-Cola Light"],
  ["Acqua minerale","2,00","1/2 L"],
  ["Pinot Serena sfuso","4,00 · 7,00 · 12,00","1/4 · 1/2 · 1 L"],
  ["Barbera Vinchio Vaglio sfusa","4,00 · 7,00 · 12,00","1/4 · 1/2 · 1 L"],
  ["Prosecco veneto","4,00","mini bottiglia 0,20 L"],
  ["Prosecco Valdobbiadene","10,00","0,375 L"],
 ]},
 {id:"vini", t:"Vini", s:"Vini", items:[
  ["Barbera d'Asti","15,00","rosso"],
  ["Freisa","15,00","rosso"],
  ["Dolcetto","15,00","rosso"],
  ["Grignolino","15,00","rosso"],
  ["Bonarda dell'Oltrepò Pavese Dione","15,00","rosso"],
  ["Barbera d'Alba","18,00","rosso"],
  ["Alghero","12,00","rosato"],
  ["Corvo","13,00","rosato"],
  ["Müller Thurgau Vigneti delle Dolomiti","15,00","bianco"],
  ["Vermentino di Sardegna","15,00","bianco"],
  ["Favorita","15,00","bianco"],
  ["Pigato ligure","18,00","bianco"],
  ["Greco di Tufo Borgotufato","18,00","bianco · anche 0,375 L a € 10,00"],
  ["Fiano d'Avellino Borgotufato","18,00","bianco"],
  ["Arneis Roero Pescaja","18,00","bianco"],
  ["Gewürztraminer","18,00","bianco"],
  ["Sauvignon del Collio","18,00","bianco"],
  ["Vermentino di Gallura","10,00","bianco · 0,375 L"],
  ["Prosecco Mionetto Corda","18,00","bollicine"],
  ["Spumante Prosecco","18,00","bollicine"],
  ["Spumante dolce Moscato","15,00","bollicine"],
 ]},
]
  },

  gallery: {
    eyebrow: "A bordo",
    title: "Benvenuti sul Titanic",
    lead: "Soffitto stellato, iceberg alle pareti e profumo di forno a legna.",
    images: [
      { src: "img/sala.webp", alt: "La sala principale" },
      { src: "img/pizza.webp", alt: "Pizza con farina macinata a pietra" },
      { src: "img/pizza-cozze.webp", alt: "Pizza con cozze" },
      { src: "img/pesce.webp", alt: "Zuppetta di mare" },
      { src: "img/grigliata.webp", alt: "Grigliata mista di pesce" }
    ]
  },

  // lunedì → domenica; [ora, min, ora, min]; [] = chiuso
  hours: [
  ["Lunedì",   [[12,0,14,30],[19,0,24,0]]],
  ["Martedì",  [[12,0,14,30],[19,0,24,0]]],
  ["Mercoledì",[]],
  ["Giovedì",  [[12,0,14,30],[19,0,24,0]]],
  ["Venerdì",  [[12,0,14,30],[19,0,24,0]]],
  ["Sabato",   [[12,0,14,30],[19,0,24,0]]],
  ["Domenica", [[12,0,14,30],[19,0,24,0]]],
],
  hoursNote: ""
};
